### ISSUE TITLE
Flush of log files

### ISSUE THREAD

**Issue by wegascee** [Belorus/XLog#3]
Now I tried XLog and found the following: If you don't have enough log entries, the entries are never written to the log file. When is the flush made? How often will it be made? How handle the case, when not so many log entries are made? You will never notice the exception/app crash ...

Some additonal questions:
- Is log rotation/file size limit used? What about parallel threads? How does this library behave here?
- Can someone describe the available targets a little bit more? What is the difference between FastFileTarget and SyncFileTarget? ConsoleTarget isn't available in UWP. Perhaps use System.Diagnostics.Debug.WriteLine instead as Target? Where is ColoredConsoleTarget available?

Thanks!

**Comment by Belorus** [comment]
Hi,

Flush should be done manually (see the WinForms sample for example). Right now flush is done every 4096 bytes i think, the default buffer size of StreamWriter.

There is no rotation/limit mechanism. If you need - this should be implemented manually. Pull requests are welcome.

Library is thread safe.

FastFileTarget is a rudimetary target, i'll remove it and SyncFileTarget will be the only file target.
ConsoleTarget is not available because there is no Console in UWP, use DelegateTarget and Debug.WriteLine.

ColoredConsoleTarget is available in .NET.
